on: [push, pull_request]

name: CMake Build

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # container: ["fedora:35"]
        openmp:
          - on
          - off
        # mkl:
        #   - on
        #   - off
    # container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v2
      - name: Add intel apt repo
        run: |
          wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          sudo add-apt-repository "deb https://apt.repos.intel.com/oneapi all main"
          sudo apt-get update
      - name: Install prerequisites
        run: sudo apt-get install -y intel-basekit intel-hpckit
      - name: Build
        run: |
          source /opt/intel/oneapi/setvars.sh
          cmake -B ${{github.workspace}}/cbuild -S .
          cmake --build ${{github.workspace}}/cbuild
      - name: Test
        shell: bash
        working-directory: ${{github.workspace}}/cbuild
        run: |
          source /opt/intel/oneapi/setvars.sh
          ctest -j10 --output-on-failure
